<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Proyecto</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Proyecto_Final_files/libs/clipboard/clipboard.min.js"></script>
<script src="Proyecto_Final_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Proyecto_Final_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Proyecto_Final_files/libs/quarto-html/popper.min.js"></script>
<script src="Proyecto_Final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Proyecto_Final_files/libs/quarto-html/anchor.min.js"></script>
<link href="Proyecto_Final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Proyecto_Final_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Proyecto_Final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Proyecto_Final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Proyecto_Final_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proyecto</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="autores" class="level2">
<h2 class="anchored" data-anchor-id="autores">Autores</h2>
<p><strong><em>“Carlos Antonio Reyes Gutiérrez, Amado Mauricio Ortega Sanchez, Arath Nava Calleros, Héctor Eduardo Muñiz Navarro”</em></strong></p>
</section>
<section id="relación-entre-el-crecimiento-económico-de-méxico-y-las-variables-macroeconómicas-clave-deuda-externa-exportaciones-reservas-internacionales-y-formación-bruta-de-capital-fijo-fbkf" class="level1">
<h1>“Relación entre el crecimiento económico de México y las variables macroeconómicas clave: deuda externa, exportaciones, reservas internacionales y formación bruta de capital fijo (FBKF)”</h1>
<section id="objetivo-general" class="level2">
<h2 class="anchored" data-anchor-id="objetivo-general">Objetivo General</h2>
<p>Evaluar la relación estadística entre variables económicas macro relevantes y el crecimiento económico de México, con base en datos provenientes del INEGI y Banco de México.</p>
</section>
<section id="objetivos-específicos" class="level2">
<h2 class="anchored" data-anchor-id="objetivos-específicos">Objetivos Específicos</h2>
<ol type="1">
<li>Describir el comportamiento histórico del PIB, PIB per cápita, deuda externa, exportaciones, reservas internacionales y FBKF.</li>
<li>Determinar la distribución estadística que mejor modela cada variable económica.</li>
<li>Estimar los parámetros poblacionales de cada variable utilizando métodos estadísticos (MOM y MLE).</li>
<li>Construir intervalos de confianza para los parámetros estimados y evaluar su precisión.</li>
<li>Plantear y realizar pruebas de hipótesis respecto a la relación entre las variables externas y el crecimiento económico.</li>
<li>Analizar si las variables externas tienen un efecto significativo en explicar el crecimiento económico de México.</li>
</ol>
</section>
<section id="hipótesis-general" class="level2">
<h2 class="anchored" data-anchor-id="hipótesis-general">Hipótesis General</h2>
<p>H1: Las variables macroeconómicas deuda externa, exportaciones, reservas internacionales y FBKF tienen un efecto estadísticamente significativo en el crecimiento económico de México. H0: Estas variables no tienen un efecto estadísticamente significativo en el crecimiento económico.</p>
<p>Datos</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"./Datos_laffer.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)          </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)     </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)    </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)       </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)       </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(strucchange)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
   ...1   Deuda_TOTAL Balance_fiscal Reservas_Internacionales     FBKF  TIIE
  &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;                    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
1  1996  678767000000        234454.                   15913. 2768150.  33.6
2  1997  661833000000        304780.                   22848. 3195461.  21.9
3  1998  822392000000         24776.                   29504. 3536752.  26.9
4  1999  951283000000         40321.                   30569. 3697841.  24.1
5  2000 1043400000000        132238.                   32409. 3879719.  17.0
6  2001 1126910000000        117174.                   38845. 3613902.  12.9
# ℹ 4 more variables: Exportaciones &lt;dbl&gt;, PIB &lt;dbl&gt;, PIB_PC &lt;dbl&gt;,
#   Deuda_Externa &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "...1"                     "Deuda_TOTAL"             
 [3] "Balance_fiscal"           "Reservas_Internacionales"
 [5] "FBKF"                     "TIIE"                    
 [7] "Exportaciones"            "PIB"                     
 [9] "PIB_PC"                   "Deuda_Externa"           </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ...1       Deuda_TOTAL        Balance_fiscal     Reservas_Internacionales
 Min.   :1996   Min.   :6.618e+11   Min.   :-8931586   Min.   : 15913          
 1st Qu.:2003   1st Qu.:1.433e+12   1st Qu.:-2245458   1st Qu.: 52857          
 Median :2010   Median :3.543e+12   Median :-1145879   Median :102914          
 Mean   :2010   Mean   :5.086e+12   Mean   :-1170185   Mean   :115285          
 3rd Qu.:2017   3rd Qu.:8.471e+12   3rd Qu.:  304780   3rd Qu.:178603          
 Max.   :2024   Max.   :1.446e+13   Max.   : 1412919   Max.   :221456          
      FBKF              TIIE        Exportaciones           PIB          
 Min.   :2768150   Min.   : 3.316   Min.   : 2954544   Min.   :13691780  
 1st Qu.:3879719   1st Qu.: 4.910   1st Qu.: 4476351   1st Qu.:16812369  
 Median :4796781   Median : 7.659   Median : 5973904   Median :19163817  
 Mean   :4660621   Mean   :10.058   Mean   : 6530152   Mean   :19413290  
 3rd Qu.:5325239   3rd Qu.:11.098   3rd Qu.: 8861145   3rd Qu.:22025297  
 Max.   :6316434   Max.   :33.607   Max.   :10412238   Max.   :23955408  
     PIB_PC       Deuda_Externa      
 Min.   :154237   Min.   :4.349e+11  
 1st Qu.:173144   1st Qu.:7.665e+11  
 Median :181457   Median :1.354e+12  
 Mean   :179666   Mean   :2.105e+12  
 3rd Qu.:186775   3rd Qu.:3.763e+12  
 Max.   :192311   Max.   :5.150e+12  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>grafico_serie <span class="ot">&lt;-</span> <span class="cf">function</span>(variable, titulo, <span class="at">unidad =</span> <span class="st">"USD"</span>) {</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> ...<span class="dv">1</span>, <span class="at">y =</span> <span class="sc">!!</span><span class="fu">sym</span>(variable))) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"darkblue"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> titulo,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Año"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="fu">paste</span>(<span class="st">"Valor ("</span>, unidad, <span class="st">")"</span>, <span class="at">sep =</span> <span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">grafico_serie</span>(<span class="st">"PIB"</span>, <span class="st">"Evolución del PIB de México"</span>, <span class="st">"Billones MXN"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">grafico_serie</span>(<span class="st">"PIB_PC"</span>, <span class="st">"Evolución del PIB per cápita"</span>, <span class="st">"Miles MXN"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">grafico_serie</span>(<span class="st">"Deuda_Externa"</span>, <span class="st">"Evolución de la Deuda Externa"</span>, <span class="st">"Miles de millones MXN"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">grafico_serie</span>(<span class="st">"Exportaciones"</span>, <span class="st">"Evolución de las Exportaciones"</span>, <span class="st">"Miles de millones MXN"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">grafico_serie</span>(<span class="st">"Reservas_Internacionales"</span>, <span class="st">"Reservas Internacionales"</span>, <span class="st">"Miles de millones USD"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">grafico_serie</span>(<span class="st">"FBKF"</span>, <span class="st">"Formación Bruta de Capital Fijo (FBKF)"</span>, <span class="st">"Miles de millones MXN"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>p7 <span class="ot">&lt;-</span> <span class="fu">grafico_serie</span>(<span class="st">"Balance_fiscal"</span>, <span class="st">"Evolución del Balance Fiscal"</span>, <span class="st">"Miles de millones MXN"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, p3, p4, p5, p6, p7, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En primer lugar, al observar la Evolución del PIB y el PIB per cápita, se identifica una clara tendencia estocástica creciente a largo plazo. Sin embargo, esta trayectoria no es lineal ni suave, la gráfica revela la alta vulnerabilidad de la economía mexicana ante choques exógenos, destacándose visualmente dos rupturas estructurales profundas correspondientes a la crisis financiera del 2008 y la caída provocada por la pandemia del COVID-19 en 2020. Estos eventos sugieren que la variable dependiente (crecimiento económico) posee una volatilidad que deberá ser considerada al momento de realizar las pruebas de hipótesis.</p>
<p>Por el lado de los componentes de la demanda agregada, el comportamiento de las Exportaciones y la Formación Bruta de Capital Fijo (FBKF) ofrece evidencia preliminar que respalda la hipótesis general del trabajo. Las exportaciones muestran una correlación visualmente fuerte y positiva con el producto, actuando como un motor de recuperación, especialmente tras la caída de 2020. Por su parte, la FBKF exhibe un comportamiento más volátil que el consumo, es notable su estancamiento en el periodo 2015-2019 previo al desplome de 2020, lo cual es relevante dado que la inversión es un determinante crucial para el crecimiento sostenido a largo plazo. La sincronización de estas caídas y recuperaciones con el PIB sugiere una relación estadísticamente significativa.</p>
<p>En cuanto a las variables financieras y de estabilidad, la Deuda Externa y el Balance Fiscal presentan un cambio de régimen evidente alrededor del año 2008. Antes de esta fecha, la deuda se mantenía relativamente estable, pero posteriormente inicia una tendencia de crecimiento acelerado, coincidiendo con un deterioro persistente en el balance fiscal déficit. Esto indica que la deuda a servido para suavizar los choques economicos de las crisis lo que nos ha llevado a caer en un ciclo de endeudamiento. Las reservas muestran que han tenido una tendencia a acumularlas esto para darle estabilidad al peso mexicano.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>calcular_tasa_crecimiento <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(x) <span class="sc">/</span> x[<span class="sc">-</span><span class="fu">length</span>(x)] <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_PIB =</span> <span class="fu">calcular_tasa_crecimiento</span>(PIB),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_PIB_PC =</span> <span class="fu">calcular_tasa_crecimiento</span>(PIB_PC),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_Export =</span> <span class="fu">calcular_tasa_crecimiento</span>(Exportaciones),</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_FBKF =</span> <span class="fu">calcular_tasa_crecimiento</span>(FBKF),</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_Balance =</span> <span class="fu">calcular_tasa_crecimiento</span>(Balance_fiscal),</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>   <span class="at">Crecimiento_Deuda =</span> <span class="fu">calcular_tasa_crecimiento</span>(Deuda_Externa)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Crecimiento_PIB)), <span class="fu">aes</span>(<span class="at">x =</span> ...<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_PIB, <span class="at">color =</span> <span class="st">"PIB"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_PIB_PC, <span class="at">color =</span> <span class="st">"PIB per cápita"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_Export, <span class="at">color =</span> <span class="st">"Exportaciones"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_FBKF, <span class="at">color =</span> <span class="st">"FBKF"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_Balance, <span class="at">color =</span> <span class="st">"Balance fiscal"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_Deuda, <span class="at">color =</span> <span class="st">"Deuda Externa"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Tasas de Crecimiento Anual (%)"</span>,</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Año"</span>,</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Tasa de Crecimiento (%)"</span>,</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Variable"</span>) <span class="sc">+</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>variables_interes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PIB"</span>, <span class="st">"PIB_PC"</span>, <span class="st">"Deuda_Externa"</span>, <span class="st">"Exportaciones"</span>, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Reservas_Internacionales"</span>, <span class="st">"FBKF"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>calcular_tasa_crecimiento <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(x) <span class="sc">/</span> x[<span class="sc">-</span><span class="fu">length</span>(x)] <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_PIB =</span> <span class="fu">calcular_tasa_crecimiento</span>(PIB),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_PIB_PC =</span> <span class="fu">calcular_tasa_crecimiento</span>(PIB_PC),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_Export =</span> <span class="fu">calcular_tasa_crecimiento</span>(Exportaciones),</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_FBKF =</span> <span class="fu">calcular_tasa_crecimiento</span>(FBKF),</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Crecimiento_Deuda =</span> <span class="fu">calcular_tasa_crecimiento</span>(Deuda_Externa)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Crecimiento_PIB)), <span class="fu">aes</span>(<span class="at">x =</span> ...<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_PIB, <span class="at">color =</span> <span class="st">"PIB"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_PIB_PC, <span class="at">color =</span> <span class="st">"PIB per cápita"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_Export, <span class="at">color =</span> <span class="st">"Exportaciones"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_FBKF, <span class="at">color =</span> <span class="st">"FBKF"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Crecimiento_Deuda, <span class="at">color =</span> <span class="st">"Deuda Externa"</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Tasas de Crecimiento Anual (%)"</span>,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Año"</span>,</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Tasa de Crecimiento (%)"</span>,</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Variable"</span>) <span class="sc">+</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>variables_interes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PIB"</span>, <span class="st">"PIB_PC"</span>, <span class="st">"Deuda_Externa"</span>, <span class="st">"Exportaciones"</span>, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Reservas_Internacionales"</span>, <span class="st">"FBKF"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Analizando la gráficas del porcentaje del crecimiento tenemos nos podemos percatar una vez mas de los impactos que han tenido las crisis en la economía mexina han sido catastroficos, se puede visualizar el pico atipico extremo cercano al 200% durante la crisis del 2008 hizo que México recurriera a la deuda externa para suavizar el impacto sin embargo no fue la mejor decisión ya que a partir de eso a lo largo del tiempo podemos ver que se ha seguido endeudandose para gnerar crecimiento pero no ha mostrado resultados.</p>
<p>Tambien podemos observar que la Formacion Bruta de Capital Fijo (FBKF) y las exportaciones muestran una alta sensibilidad al ciclo económico. Particularmente, la inversión (FBKF) y las exportaciones actúan como componentes pro-cíclicos, contrayéndose severamente durante las recesiones y liderando la recuperación posterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>variables_interes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PIB"</span>, <span class="st">"PIB_PC"</span>, <span class="st">"Deuda_Externa"</span>, <span class="st">"Exportaciones"</span>, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Reservas_Internacionales"</span>, <span class="st">"FBKF"</span>, <span class="st">"Balance_fiscal"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>correlaciones <span class="ot">&lt;-</span> <span class="fu">cor</span>(datos[, variables_interes], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Matriz de correlaciones:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Matriz de correlaciones:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(correlaciones, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           PIB PIB_PC Deuda_Externa Exportaciones
PIB                       1.00   0.87          0.85          0.98
PIB_PC                    0.87   1.00          0.58          0.78
Deuda_Externa             0.85   0.58          1.00          0.93
Exportaciones             0.98   0.78          0.93          1.00
Reservas_Internacionales  0.96   0.73          0.89          0.97
FBKF                      0.94   0.88          0.67          0.87
Balance_fiscal           -0.67  -0.43         -0.71         -0.70
                         Reservas_Internacionales  FBKF Balance_fiscal
PIB                                          0.96  0.94          -0.67
PIB_PC                                       0.73  0.88          -0.43
Deuda_Externa                                0.89  0.67          -0.71
Exportaciones                                0.97  0.87          -0.70
Reservas_Internacionales                     1.00  0.89          -0.74
FBKF                                         0.89  1.00          -0.64
Balance_fiscal                              -0.74 -0.64           1.00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(correlaciones, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">type =</span> <span class="st">"upper"</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Correlaciones entre Variables Macroeconómicas"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En la matriz de correlación se observa que las Exportaciones, las Reservas Internacionales y la Deuda Externa presentan coeficientes de correlación cercanos a la unidad representados en azul intenso, lo cual sugiere, en una primera instancia, que existe una sincronización casi perfecta entre el crecimiento de estas variables y la expansión del producto nacional. Esta evidencia descriptiva respalda preliminarmente la hipótesis general de trabajo (<span class="math inline">\(H_1\)</span>), indicando que estas variables macroeconómicas poseen un alto poder predictivo sobre el desempeño económico de México durante el periodo que estamos estudiando.</p>
<p>No obstante,también expone una relación inversa significativa color rojo intenso entre el Balance Fiscal y el resto de las variables de crecimiento. Esto implica que la expansión histórica del PIB y el aumento de la inversión (FBKF) han estado acompañados sistemáticamente por un deterioro en las finanzas públicas mayores déficits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>estimacion_mom <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">distribucion =</span> <span class="st">"normal"</span>) {</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(distribucion <span class="sc">==</span> <span class="st">"normal"</span>) {</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    sigma2 <span class="ot">&lt;-</span> <span class="fu">var</span>(x) <span class="sc">*</span> (n<span class="dv">-1</span>)<span class="sc">/</span>n</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">list</span>(<span class="at">mu =</span> mu, <span class="at">sigma2 =</span> sigma2, <span class="at">sigma =</span> <span class="fu">sqrt</span>(sigma2)))</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(distribucion <span class="sc">==</span> <span class="st">"lognormal"</span>) {</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">log</span>(x))</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    sigma2 <span class="ot">&lt;-</span> <span class="fu">var</span>(<span class="fu">log</span>(x)) <span class="sc">*</span> (n<span class="dv">-1</span>)<span class="sc">/</span>n</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">list</span>(<span class="at">mu =</span> mu, <span class="at">sigma2 =</span> sigma2, <span class="at">sigma =</span> <span class="fu">sqrt</span>(sigma2)))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>estimacion_mle <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">distribucion =</span> <span class="st">"normal"</span>) {</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(distribucion <span class="sc">==</span> <span class="st">"normal"</span>) {</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>    sigma2 <span class="ot">&lt;-</span> <span class="fu">var</span>(x)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">list</span>(<span class="at">mu =</span> mu, <span class="at">sigma2 =</span> sigma2, <span class="at">sigma =</span> <span class="fu">sqrt</span>(sigma2)))</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(distribucion <span class="sc">==</span> <span class="st">"lognormal"</span>) {</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">log</span>(x))</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>    sigma2 <span class="ot">&lt;-</span> <span class="fu">var</span>(<span class="fu">log</span>(x))</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">list</span>(<span class="at">mu =</span> mu, <span class="at">sigma2 =</span> sigma2, <span class="at">sigma =</span> <span class="fu">sqrt</span>(sigma2)))</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pib-per-cápita-log-normal" class="level2">
<h2 class="anchored" data-anchor-id="pib-per-cápita-log-normal">PIB PER CÁPITA (LOG NORMAL)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>pib_pc_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>PIB_PC)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>resultados_pib_pc_mom <span class="ot">&lt;-</span> <span class="fu">estimacion_mom</span>(pib_pc_data, <span class="st">"lognormal"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>resultados_pib_pc_mle <span class="ot">&lt;-</span> <span class="fu">estimacion_mle</span>(pib_pc_data, <span class="st">"lognormal"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(pib_pc_data, <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="at">breaks =</span> <span class="dv">15</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"PIB per cápita - Ajuste Lognormal"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"PIB per cápita"</span>, </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rgb</span>(<span class="fl">0.8</span>, <span class="fl">0.8</span>, <span class="fl">0.8</span>, <span class="fl">0.5</span>), </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"white"</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>x_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(pib_pc_data), <span class="fu">max</span>(pib_pc_data), <span class="at">length =</span> <span class="dv">200</span>)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_seq, <span class="fu">dlnorm</span>(x_seq, <span class="at">meanlog =</span> resultados_pib_pc_mom<span class="sc">$</span>mu, </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sdlog =</span> resultados_pib_pc_mom<span class="sc">$</span>sigma),</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_seq, <span class="fu">dlnorm</span>(x_seq, <span class="at">meanlog =</span> resultados_pib_pc_mle<span class="sc">$</span>mu, </span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sdlog =</span> resultados_pib_pc_mle<span class="sc">$</span>sigma),</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Datos"</span>, <span class="st">"MOM"</span>, <span class="st">"MLE"</span>),</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"gray"</span>, <span class="st">"red"</span>, <span class="st">"blue"</span>),</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="fu">c</span>(<span class="fu">rgb</span>(<span class="fl">0.8</span>, <span class="fl">0.8</span>, <span class="fl">0.8</span>, <span class="fl">0.5</span>), <span class="cn">NA</span>, <span class="cn">NA</span>),</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El análisis de la distribución empírica del PIB per cápita, representado mediante el histograma de frecuencias, revela una estructura de datos compleja que se aleja de una simetría perfecta. Se observa una dispersión considerable en el rango de 160,000 a 190,000 pesos, con concentraciones de frecuencia que sugieren la presencia de distintos regímenes económicos a lo largo del tiempo. Las barras del histograma no forman una campana suave y continua, sino que presentan vacíos y picos irregulares, esto es consistente con el análisis de series de tiempo previo, donde identificamos que la economía mexicana ha sufrido choques estructurales como las crisis de 2008 y 2020 que alteran la continuidad de los datos y generan estas irregularidades en la distribución de probabilidad observada.</p>
<p>Para modelar este comportamiento, se seleccionó la Distribución Lognormal, una elección teóricamente robusta para variables económicas monetarias que, por definición, no pueden ser negativas y suelen presentar sesgo a la derecha. En la gráfica se contrastan dos curvas de ajuste: la línea roja sólida correspondiente al Método de Momentos (MOM) y la línea azul punteada correspondiente al Método de Máxima Verosimilitud (MLE). Un hallazgo estadístico fundamental es la convergencia casi perfecta de ambos estimadores, las curvas se superponen de tal manera que son prácticamente indistinguibles. Esto indica que, a pesar de la volatilidad histórica, los parámetros estimados media y varianza logarítmica son consistentes y estables, independientemente del método de inferencia utilizado.</p>
</section>
<section id="deuda-externa-log-normal" class="level2">
<h2 class="anchored" data-anchor-id="deuda-externa-log-normal">DEUDA EXTERNA (LOG NORMAL)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>deuda_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>Deuda_Externa)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">any</span>(deuda_data <span class="sc">&lt;=</span> <span class="dv">0</span>)) {</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  deuda_data <span class="ot">&lt;-</span> deuda_data <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(deuda_data)) <span class="sc">+</span> <span class="fl">0.01</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>resultados_deuda_mom <span class="ot">&lt;-</span> <span class="fu">estimacion_mom</span>(deuda_data, <span class="st">"lognormal"</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>resultados_deuda_mle <span class="ot">&lt;-</span> <span class="fu">estimacion_mle</span>(deuda_data, <span class="st">"lognormal"</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(deuda_data, <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="at">breaks =</span> <span class="dv">15</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Deuda Externa - Ajuste Lognormal"</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Deuda Externa"</span>, </span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rgb</span>(<span class="fl">0.8</span>, <span class="fl">0.8</span>, <span class="fl">0.8</span>, <span class="fl">0.5</span>), </span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"white"</span>)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>x_seq_deuda <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(deuda_data), <span class="fu">max</span>(deuda_data), <span class="at">length =</span> <span class="dv">200</span>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_seq_deuda, <span class="fu">dlnorm</span>(x_seq_deuda, <span class="at">meanlog =</span> resultados_deuda_mom<span class="sc">$</span>mu, </span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sdlog =</span> resultados_deuda_mom<span class="sc">$</span>sigma),</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_seq_deuda, <span class="fu">dlnorm</span>(x_seq_deuda, <span class="at">meanlog =</span> resultados_deuda_mle<span class="sc">$</span>mu, </span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sdlog =</span> resultados_deuda_mle<span class="sc">$</span>sigma),</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Datos"</span>, <span class="st">"MOM"</span>, <span class="st">"MLE"</span>),</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"gray"</span>, <span class="st">"red"</span>, <span class="st">"blue"</span>),</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="fu">c</span>(<span class="fu">rgb</span>(<span class="fl">0.8</span>, <span class="fl">0.8</span>, <span class="fl">0.8</span>, <span class="fl">0.5</span>), <span class="cn">NA</span>, <span class="cn">NA</span>),</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El histograma de frecuencias de la Deuda Externa revela una estructura de datos radicalmente distinta a la del PIB per cápita, caracterizada por una fuerte asimetría positiva sesgo a la derecha. Se observa una concentración masiva de observaciones en los niveles bajos de deuda barra gris izquierda, que corresponde históricamente al largo periodo de estabilidad previo a 2008. Posteriormente, los datos se dispersan hacia la derecha alcanzando niveles de hasta 5 billones escala de <span class="math inline">\(10^{12}\)</span>, con vacíos notables entre las barras. Estos huecos en el histograma no son errores, sino el reflejo estadístico de los cambios abruptos de política económica: la deuda no creció gradualmente, sino que dio saltos discretos durante las crisis, dejando regiones de valores intermedios sin observaciones frecuentes.</p>
<p>Al aplicar la distribución Lognormal para modelar este comportamiento, se confirma nuevamente la convergencia asintótica entre los estimadores del Método de Momentos (MOM) y de Máxima Verosimilitud (MLE). Ambas curvas roja y azul se superponen con exactitud, lo que valida matemáticamente el cálculo de los parámetros de media y varianza. La elección de la distribución Lognormal es teóricamente adecuada, dado que la deuda es una variable monetaria no negativa con un crecimiento exponencial. La curva intenta capturar la tendencia general asignando la mayor probabilidad a los valores bajos y extendiendo una “cola pesada” hacia la derecha para cubrir los niveles actuales de endeudamiento.</p>
<p>Sin embargo, desde una perspectiva crítica del ajuste, es importante notar que una distribución unimodal suave como la Lognormal enfrenta dificultades para capturar la naturaleza “a saltos” de la deuda mexicana. Si bien los estimadores son consistentes, la varianza estimada es muy alta debido a la dispersión extrema de los datos hacia la cola derecha.</p>
</section>
<section id="tabla-comparativa" class="level2">
<h2 class="anchored" data-anchor-id="tabla-comparativa">TABLA COMPARATIVA</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>pib_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>PIB)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>pib_pc_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>PIB_PC)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>deuda_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>Deuda_Externa)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>export_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>Exportaciones)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>reservas_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>Reservas_Internacionales)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>fbkf_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>FBKF)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>balance_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>Balance_fiscal)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">any</span>(deuda_data <span class="sc">&lt;=</span> <span class="dv">0</span>)) {</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  deuda_data <span class="ot">&lt;-</span> deuda_data <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(deuda_data)) <span class="sc">+</span> <span class="fl">0.01</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>resultados <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>PIB_mom <span class="ot">&lt;-</span> <span class="fu">estimacion_mom</span>(pib_data, <span class="st">"normal"</span>)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>PIB_mle <span class="ot">&lt;-</span> <span class="fu">estimacion_mle</span>(pib_data, <span class="st">"normal"</span>)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>PIB_PC_mom <span class="ot">&lt;-</span> <span class="fu">estimacion_mom</span>(pib_pc_data, <span class="st">"lognormal"</span>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>PIB_PC_mle <span class="ot">&lt;-</span> <span class="fu">estimacion_mle</span>(pib_pc_data, <span class="st">"lognormal"</span>)</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>Deuda_mom <span class="ot">&lt;-</span> <span class="fu">estimacion_mom</span>(deuda_data, <span class="st">"lognormal"</span>)</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>Deuda_mle <span class="ot">&lt;-</span> <span class="fu">estimacion_mle</span>(deuda_data, <span class="st">"lognormal"</span>)</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>Export_mom <span class="ot">&lt;-</span> <span class="fu">estimacion_mom</span>(export_data, <span class="st">"normal"</span>)</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>Export_mle <span class="ot">&lt;-</span> <span class="fu">estimacion_mle</span>(export_data, <span class="st">"normal"</span>)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>FBKF_mom <span class="ot">&lt;-</span> <span class="fu">estimacion_mom</span>(fbkf_data, <span class="st">"normal"</span>)</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>FBKF_mle <span class="ot">&lt;-</span> <span class="fu">estimacion_mle</span>(fbkf_data, <span class="st">"normal"</span>)</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>Balance_mom <span class="ot">&lt;-</span> <span class="fu">estimacion_mom</span>(balance_data, <span class="st">"normal"</span>)</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>resultados<span class="sc">$</span>Balance_mle <span class="ot">&lt;-</span> <span class="fu">estimacion_mle</span>(balance_data, <span class="st">"normal"</span>)</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>tabla_comparativa <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"PIB"</span>, <span class="st">"PIB_PC"</span>, <span class="st">"Deuda_Externa"</span>, <span class="st">"Exportaciones"</span>, <span class="st">"FBKF"</span>, <span class="st">"Balance_fiscal"</span>), <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>  Método <span class="ot">=</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"MOM"</span>, <span class="st">"MLE"</span>), <span class="dv">6</span>),</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>  Distribución <span class="ot">=</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Lognormal"</span>, <span class="st">"Lognormal"</span>, <span class="st">"Normal"</span>, <span class="st">"Normal"</span>, <span class="st">"Normal"</span>), <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>  μ <span class="ot">=</span> <span class="fu">c</span>(resultados<span class="sc">$</span>PIB_mom<span class="sc">$</span>mu, resultados<span class="sc">$</span>PIB_mle<span class="sc">$</span>mu,</span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>PIB_PC_mom<span class="sc">$</span>mu, resultados<span class="sc">$</span>PIB_PC_mle<span class="sc">$</span>mu,</span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>Deuda_mom<span class="sc">$</span>mu, resultados<span class="sc">$</span>Deuda_mle<span class="sc">$</span>mu,</span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>Export_mom<span class="sc">$</span>mu, resultados<span class="sc">$</span>Export_mle<span class="sc">$</span>mu,</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>FBKF_mom<span class="sc">$</span>mu, resultados<span class="sc">$</span>FBKF_mle<span class="sc">$</span>mu,</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>Balance_mom<span class="sc">$</span>mu, resultados<span class="sc">$</span>Balance_mle<span class="sc">$</span>mu),</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>  σ <span class="ot">=</span> <span class="fu">c</span>(resultados<span class="sc">$</span>PIB_mom<span class="sc">$</span>sigma, resultados<span class="sc">$</span>PIB_mle<span class="sc">$</span>sigma,</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>PIB_PC_mom<span class="sc">$</span>sigma, resultados<span class="sc">$</span>PIB_PC_mle<span class="sc">$</span>sigma,</span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>Deuda_mom<span class="sc">$</span>sigma, resultados<span class="sc">$</span>Deuda_mle<span class="sc">$</span>sigma,</span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>Export_mom<span class="sc">$</span>sigma, resultados<span class="sc">$</span>Export_mle<span class="sc">$</span>sigma,</span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>FBKF_mom<span class="sc">$</span>sigma, resultados<span class="sc">$</span>FBKF_mle<span class="sc">$</span>sigma,</span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a>        resultados<span class="sc">$</span>Balance_mom<span class="sc">$</span>sigma, resultados<span class="sc">$</span>Balance_mle<span class="sc">$</span>sigma)</span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-50"><a href="#cb25-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-51"><a href="#cb25-51" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tabla_comparativa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Variable Método Distribución             μ            σ
1             PIB    MOM       Normal  1.941329e+07 2.819249e+06
2             PIB    MLE       Normal  1.941329e+07 2.869151e+06
3          PIB_PC    MOM    Lognormal  1.209761e+01 5.035354e-02
4          PIB_PC    MLE    Lognormal  1.209761e+01 5.124483e-02
5   Deuda_Externa    MOM    Lognormal  2.807260e+01 7.871766e-01
6   Deuda_Externa    MLE    Lognormal  2.807260e+01 8.011100e-01
7   Exportaciones    MOM       Normal  6.530152e+06 2.322485e+06
8   Exportaciones    MLE       Normal  6.530152e+06 2.363594e+06
9            FBKF    MOM       Normal  4.660621e+06 8.978336e+05
10           FBKF    MLE       Normal  4.660621e+06 9.137257e+05
11 Balance_fiscal    MOM       Normal -1.170185e+06 2.210011e+06
12 Balance_fiscal    MLE       Normal -1.170185e+06 2.249129e+06</code></pre>
</div>
</div>
<p>La tabla de resultados presenta la estimación puntual de los parámetros poblacionales media <span class="math inline">\(\mu\)</span> y desviación estándar <span class="math inline">\(\sigma\)</span> para las variables clave del estudio, contrastando dos metodologías inferenciales distintas: el Método de Momentos (MOM) y el Método de Máxima Verosimilitud (MLE). Un hallazgo transversal y estadísticamente robusto es la notable convergencia entre ambos estimadores. Para todas las variables analizadas, las medias estimadas <span class="math inline">\(\mu\)</span> son idénticas hasta el sexto decimal, y las desviaciones estándar <span class="math inline">\(\sigma\)</span> presentan diferencias marginales. Esta similitud valida la calidad de la muestra y sugiere que, a pesar de la volatilidad económica observada en las gráficas anteriores, los datos contienen información suficiente para que ambos métodos arriben a las mismas conclusiones paramétricas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ic_media_normal <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">confianza =</span> <span class="fl">0.95</span>) {</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  media <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  desv <span class="ot">&lt;-</span> <span class="fu">sd</span>(x)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  t_valor <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> confianza)<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> n<span class="dv">-1</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  lim_inf <span class="ot">&lt;-</span> media <span class="sc">-</span> t_valor <span class="sc">*</span> desv<span class="sc">/</span><span class="fu">sqrt</span>(n)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  lim_sup <span class="ot">&lt;-</span> media <span class="sc">+</span> t_valor <span class="sc">*</span> desv<span class="sc">/</span><span class="fu">sqrt</span>(n)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(lim_inf, media, lim_sup))</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>ic_varianza_normal <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">confianza =</span> <span class="fl">0.95</span>) {</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  s2 <span class="ot">&lt;-</span> <span class="fu">var</span>(x)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  chi2_inf <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> confianza)<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> n<span class="dv">-1</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  chi2_sup <span class="ot">&lt;-</span> <span class="fu">qchisq</span>((<span class="dv">1</span> <span class="sc">-</span> confianza)<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> n<span class="dv">-1</span>)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  lim_inf <span class="ot">&lt;-</span> ((n<span class="dv">-1</span>) <span class="sc">*</span> s2) <span class="sc">/</span> chi2_inf</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  lim_sup <span class="ot">&lt;-</span> ((n<span class="dv">-1</span>) <span class="sc">*</span> s2) <span class="sc">/</span> chi2_sup</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(lim_inf, s2, lim_sup))</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>ic_bootstrap <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">confianza =</span> <span class="fl">0.95</span>, <span class="at">R =</span> <span class="dv">1000</span>) {</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(boot)</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>  boot_mean <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">mean</span>(data[indices]))</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>  boot_result <span class="ot">&lt;-</span> <span class="fu">boot</span>(x, boot_mean, <span class="at">R =</span> R)</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>  ic_percentil <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(boot_result, <span class="at">conf =</span> confianza, <span class="at">type =</span> <span class="st">"perc"</span>)</span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(ic_percentil<span class="sc">$</span>percent[<span class="dv">4</span>], <span class="fu">mean</span>(x), ic_percentil<span class="sc">$</span>percent[<span class="dv">5</span>]))</span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tabla-resumen-intervalos" class="level2">
<h2 class="anchored" data-anchor-id="tabla-resumen-intervalos">TABLA RESUMEN INTERVALOS</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>variables_clave <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PIB"</span>, <span class="st">"PIB_PC"</span>, <span class="st">"Deuda_Externa"</span>, <span class="st">"Exportaciones"</span>, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Reservas_Internacionales"</span>, <span class="st">"FBKF"</span>, <span class="st">"Balance_fiscal"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>resultados_lista <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(var <span class="cf">in</span> variables_clave) {</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(var <span class="sc">%in%</span> <span class="fu">colnames</span>(datos)) {</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    datos_var <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos[[var]])</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(<span class="fu">length</span>(datos_var) <span class="sc">&gt;</span> <span class="dv">10</span>) {</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>      ic_media <span class="ot">&lt;-</span> <span class="fu">ic_media_normal</span>(datos_var, <span class="fl">0.95</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>      resultados_lista[[var]] <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">Estimacion =</span> ic_media[<span class="dv">2</span>],</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">IC95_Inferior =</span> ic_media[<span class="dv">1</span>],</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">IC95_Superior =</span> ic_media[<span class="dv">3</span>],</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">Amplitud =</span> ic_media[<span class="dv">3</span>] <span class="sc">-</span> ic_media[<span class="dv">1</span>]</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>matriz_resultados <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, resultados_lista)</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Intervalos de confianza 95% para medias:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Intervalos de confianza 95% para medias:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(matriz_resultados, <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            Estimacion IC95_Inferior IC95_Superior     Amplitud
PIB                       1.941329e+07  1.832192e+07  2.050466e+07 2.182733e+06
PIB_PC                    1.796663e+05  1.762415e+05  1.830911e+05 6.849599e+03
Deuda_Externa             2.104546e+12  1.491257e+12  2.717834e+12 1.226578e+12
Exportaciones             6.530152e+06  5.631089e+06  7.429216e+06 1.798126e+06
Reservas_Internacionales  1.152853e+05  8.880505e+04  1.417656e+05 5.296058e+04
FBKF                      4.660621e+06  4.313059e+06  5.008184e+06 6.951253e+05
Balance_fiscal           -1.170185e+06 -2.025708e+06 -3.146623e+05 1.711046e+06</code></pre>
</div>
</div>
<p>Cuando calculamos los intervalos de confianza al 95% para medir qué tan seguros podíamos estar de nuestros promedios, nos encontramos con una disparidad enorme entre las variables. Mientras que el PIB per cápita se mantiene en un rango bastante acotado lo que refleja cierta estabilidad histórica, la Deuda Externa es el caso opuesto. Nos llamó mucho la atención que su intervalo es el más amplio y borroso de todos, con una amplitud gigantesca de <span class="math inline">\(1.22 \times 10^{12}\)</span>. Esto confirma estadísticamente lo que sospechábamos al ver las gráficas: la deuda no fluctúa suavemente, sino que da saltos tan bruscos que intentar pronosticarla usando solo su promedio histórico es sumamente arriesgado debido a su inmensa volatilidad.</p>
<p>Por otro lado, encontramos un foco rojo muy claro en la sostenibilidad fiscal. Al analizar el Balance Fiscal, nos dimos cuenta de que es la única variable cuyo intervalo de confianza cae completamente en terreno negativo. Incluso en su límite superior que sería el mejor escenario estadístico con 95% de confianza, seguimos viendo números rojos de <span class="math inline">\(-3.14 \times 10^5\)</span>. Esto nos permite, rechazar la idea de que el balance promedio sea cero o positivo, la evidencia es contundente al mostrar que existe un déficit estructural. Básicamente, los datos nos dicen que el gobierno gasta sistemáticamente más de lo que ingresa, lo cual valida por qué el país necesita financiamiento externo constante.</p>
<p>Finalmente, algo que le da mucha solidez a nuestro modelo es el comportamiento de las variables de la “economía real”. Tanto el PIB como las Exportaciones y la Inversión (FBKF) mostraron intervalos de confianza bastante estrechos y consistentes. Por ejemplo, el intervalo del PIB entre <span class="math inline">\(1.83\)</span> y <span class="math inline">\(2.05 \times 10^7\)</span> es lo suficientemente preciso para usar la media estimada como una referencia confiable. Al contrastar esto con la inestabilidad de la Deuda, llegamos a la conclusión de que la economía productiva de México es mucho más estable y predecible que su estructura financiera.</p>
</section>
<section id="gráfico-comparativo-deuda-externa" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-comparativo-deuda-externa">GRÁFICO COMPARATIVO DEUDA EXTERNA</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>deuda_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>Deuda_Externa)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>ic_t <span class="ot">&lt;-</span> <span class="fu">ic_media_normal</span>(deuda_data, <span class="fl">0.95</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>ic_boot <span class="ot">&lt;-</span> <span class="fu">ic_bootstrap</span>(deuda_data, <span class="fl">0.95</span>, <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'boot'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    logit</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:survival':

    aml</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="fu">c</span>(ic_t[<span class="dv">2</span>], ic_boot[<span class="dv">2</span>]), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>), </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">2.5</span>), <span class="at">ylim =</span> <span class="fu">range</span>(<span class="fu">c</span>(ic_t[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], ic_boot[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)])),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Método"</span>, <span class="at">ylab =</span> <span class="st">"Deuda Externa"</span>, <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Comparación IC: t-Student vs Bootstrap (Deuda Externa)"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"t-Student"</span>, <span class="st">"Bootstrap"</span>))</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="dv">1</span>, ic_t[<span class="dv">1</span>], <span class="dv">1</span>, ic_t[<span class="dv">3</span>], <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="fl">0.9</span>, ic_t[<span class="dv">1</span>], <span class="fl">1.1</span>, ic_t[<span class="dv">1</span>], <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="fl">0.9</span>, ic_t[<span class="dv">3</span>], <span class="fl">1.1</span>, ic_t[<span class="dv">3</span>], <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="dv">2</span>, ic_boot[<span class="dv">1</span>], <span class="dv">2</span>, ic_boot[<span class="dv">3</span>], <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="fl">1.9</span>, ic_boot[<span class="dv">1</span>], <span class="fl">2.1</span>, ic_boot[<span class="dv">1</span>], <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="fl">1.9</span>, ic_boot[<span class="dv">3</span>], <span class="fl">2.1</span>, ic_boot[<span class="dv">3</span>], <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> ic_boot[<span class="dv">2</span>], <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"t-Student"</span>, <span class="st">"Bootstrap"</span>, <span class="st">"Media Bootstrap"</span>),</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>, <span class="st">"red"</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">19</span>, <span class="cn">NA</span>),</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En esta gráfica quisimos poner a prueba qué tan confiables son nuestras estimaciones de la Deuda Externa. Como vimos antes que los datos de la deuda no se comportan como una campana normal perfecta y tienen saltos bruscos. Comparamos el intervalo calculado con la t-Student la línea azul contra el método de Bootstrap la línea roja, que funciona haciendo miles de simulaciones con los mismos datos para ver qué pasa sin asumir tantas reglas teóricas.</p>
<p>Lo que se ve en la imagen los bigotes las líneas verticales de ambos métodos son casi del mismo tamaño y caen prácticamente en el mismo rango. La media el punto en el centro también coincide perfecto con la línea roja punteada. Esto significa que, aunque la deuda tenga una distribución complicada, el cálculo del intervalo es robusto.</p>
<p>Básicamente, el Bootstrap vino a confirmar lo que nos dijo la t-Student. Si los resultados hubieran salido muy diferentes por ejemplo, si la línea roja estuviera muy lejos de la azul, tendriamos que preocuparnos por la validez de los datos, pero como se traslapan casi exacto, podemos decir con seguridad que el verdadero valor promedio de la deuda externa sí cae dentro de esos límites enormes que calculamos, sin importar qué método usemos.</p>
</section>
</section>
<section id="intervalos-de-confianza-para-pib-per-cápita" class="level1">
<h1>INTERVALOS DE CONFIANZA PARA PIB PER CÁPITA</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>pib_pc_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos<span class="sc">$</span>PIB_PC)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>n_pib_pc <span class="ot">&lt;-</span> <span class="fu">length</span>(pib_pc_data)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>media_pib_pc <span class="ot">&lt;-</span> <span class="fu">mean</span>(pib_pc_data)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>sd_pib_pc <span class="ot">&lt;-</span> <span class="fu">sd</span>(pib_pc_data)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>log_pib_pc <span class="ot">&lt;-</span> <span class="fu">log</span>(pib_pc_data)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>ic_log_media <span class="ot">&lt;-</span> <span class="fu">ic_media_normal</span>(log_pib_pc, <span class="at">confianza =</span> <span class="fl">0.95</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>ic_log_var <span class="ot">&lt;-</span> <span class="fu">ic_varianza_normal</span>(log_pib_pc, <span class="at">confianza =</span> <span class="fl">0.95</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>media_geom <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">mean</span>(log_pib_pc))</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>ic_media_original <span class="ot">&lt;-</span> <span class="fu">exp</span>(ic_log_media[<span class="dv">1</span>])</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>ic_media_original_sup <span class="ot">&lt;-</span> <span class="fu">exp</span>(ic_log_media[<span class="dv">3</span>])</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>ic_normal_directo <span class="ot">&lt;-</span> <span class="fu">ic_media_normal</span>(pib_pc_data, <span class="at">confianza =</span> <span class="fl">0.95</span>)</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>comparacion_pib_pc <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Metodo =</span> <span class="fu">c</span>(<span class="st">"Lognormal"</span>, <span class="st">"Normal Directa"</span>),</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">Media =</span> <span class="fu">c</span>(media_geom, ic_normal_directo[<span class="dv">2</span>]),</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC95_Inferior =</span> <span class="fu">c</span>(ic_media_original, ic_normal_directo[<span class="dv">1</span>]),</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC95_Superior =</span> <span class="fu">c</span>(ic_media_original_sup, ic_normal_directo[<span class="dv">3</span>])</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(comparacion_pib_pc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Metodo    Media IC95_Inferior IC95_Superior
1      Lognormal 179442.1      175978.2      182974.2
2 Normal Directa 179666.3      176241.5      183091.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, comparacion_pib_pc<span class="sc">$</span>Media, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">2.5</span>), <span class="at">ylim =</span> <span class="fu">range</span>(comparacion_pib_pc[,<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>]),</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Método"</span>, <span class="at">ylab =</span> <span class="st">"PIB per cápita"</span>, <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Comparación IC: Lognormal vs Normal"</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">labels =</span> comparacion_pib_pc<span class="sc">$</span>Metodo)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, comparacion_pib_pc<span class="sc">$</span>IC95_Inferior, </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>         <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, comparacion_pib_pc<span class="sc">$</span>IC95_Superior, </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, comparacion_pib_pc<span class="sc">$</span>IC95_Inferior, <span class="at">pch =</span> <span class="dv">25</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">bg =</span> <span class="st">"red"</span>, <span class="at">cex =</span> <span class="dv">1</span>)</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, comparacion_pib_pc<span class="sc">$</span>IC95_Superior, <span class="at">pch =</span> <span class="dv">24</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">bg =</span> <span class="st">"red"</span>, <span class="at">cex =</span> <span class="dv">1</span>)</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(pib_pc_data), <span class="at">col =</span> <span class="st">"gray"</span>, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En esta parte quisimos hacer un experimento para ver qué tanto afectaba la elección de la distribución teórica a los resultados del PIB per cápita. Comparamos el intervalo de confianza calculado asumiendo una Distribución Lognormal que se supone es la ideal para dinero y salarios contra una Distribución Normal estándar.</p>
<p>Lo que muestra la gráfica es que las dos barras son prácticamente gemelas.Los puntos azules que son las medias estimadas están casi a la misma altura, y las flechas rojas que marcan hasta dónde llega el intervalo de confianza son casi idénticas en ambos casos. Esto significa que los datos del PIB per cápita son lo suficientemente nobles como para que no importe tanto qué método matemático se use, el resultado central no cambia drásticamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos[<span class="fu">order</span>(datos<span class="sc">$</span>...<span class="dv">1</span>), ]</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>Crecimiento_PIB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(datos<span class="sc">$</span>PIB) <span class="sc">/</span> datos<span class="sc">$</span>PIB[<span class="sc">-</span><span class="fu">nrow</span>(datos)] <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>variables_externas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Exportaciones"</span>, <span class="st">"Deuda_Externa"</span>, <span class="st">"Reservas_Internacionales"</span>, </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"FBKF"</span>, <span class="st">"TIIE"</span>, <span class="st">"Balance_fiscal"</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>datos_limpios <span class="ot">&lt;-</span> datos[<span class="fu">complete.cases</span>(datos[, <span class="fu">c</span>(<span class="st">"Crecimiento_PIB"</span>, variables_externas)]), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pruebas-de-hipótesis" class="level1">
<h1>PRUEBAS DE HIPÓTESIS</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>alta_deuda <span class="ot">&lt;-</span> datos_limpios<span class="sc">$</span>Deuda_Externa <span class="sc">&gt;</span> <span class="fu">median</span>(datos_limpios<span class="sc">$</span>Deuda_Externa)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>test_deb <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Crecimiento_PIB <span class="sc">~</span> alta_deuda, <span class="at">data =</span> datos_limpios, <span class="at">alternative =</span> <span class="st">"less"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>alta_tiie <span class="ot">&lt;-</span> datos_limpios<span class="sc">$</span>TIIE <span class="sc">&gt;</span> <span class="fu">median</span>(datos_limpios<span class="sc">$</span>TIIE)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>test_tiie <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Crecimiento_PIB <span class="sc">~</span> alta_tiie, <span class="at">data =</span> datos_limpios)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>resultados_hipotesis <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Hipotesis =</span> <span class="fu">c</span>(<span class="st">"Deuda alta → Menor crecimiento"</span>, <span class="st">"TIIE alto afecta crecimiento"</span>),</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Estadistico =</span> <span class="fu">c</span>(<span class="fu">round</span>(test_deb<span class="sc">$</span>statistic, <span class="dv">3</span>), <span class="fu">round</span>(test_tiie<span class="sc">$</span>statistic, <span class="dv">3</span>)),</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_valor =</span> <span class="fu">c</span>(<span class="fu">round</span>(test_deb<span class="sc">$</span>p.value, <span class="dv">4</span>), <span class="fu">round</span>(test_tiie<span class="sc">$</span>p.value, <span class="dv">4</span>)),</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Resultado =</span> <span class="fu">c</span>(<span class="fu">ifelse</span>(test_deb<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Rechaza H0"</span>, <span class="st">"No rechaza"</span>),</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>                <span class="fu">ifelse</span>(test_tiie<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Rechaza H0"</span>, <span class="st">"No rechaza"</span>))</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(resultados_hipotesis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Hipotesis Estadistico P_valor  Resultado
1 Deuda alta → Menor crecimiento        0.56  0.7097 No rechaza
2   TIIE alto afecta crecimiento       -0.63  0.5354 No rechaza</code></pre>
</div>
</div>
<p>Resultados de nuestras Pruebas de Hipótesis Llegamos a la parte decisiva del proyecto, donde pusimos a prueba nuestras teorías usando los datos. Aquí fue donde los resultados nos sorprendieron un poco y nos obligaron a repensar lo que esperábamos encontrar.</p>
<p>Primero, planteamos la hipótesis de que Una Deuda Externa alta provoca un menor crecimiento económico. Nuestra lógica, basada en la teoría, era que si el país debe mucho dinero, debería crecer menos. Sin embargo, al correr la prueba estadística, el P-valor nos dio altísimo 0.7097. Como este valor es mucho mayor a 0.05, no tenemos evidencia estadística para rechazar la hipótesis nula.</p>
<p>Básicamente, que los datos no respaldan la idea de que la deuda por sí sola frene el crecimiento de golpe. Creemos que esto pasa porque, como vimos en las gráficas anteriores, México ha usado la deuda para salvar la economía en momentos de crisis como en 2009 y 2020. Entonces, en lugar de ver una relación negativa simple, los datos muestran que la deuda sube cuando el gobierno intenta reactivar el PIB, lo que hace que la relación estadística no sea tan directa como pensábamos.</p>
<p>También quisimos ver si la Tasa de Interés (TIIE) afectaba significativamente el crecimiento. Aquí nos pasó algo similar: obtuvimos un estadístico de -0.63 y un P-valor de 0.5354. Nuevamente, el resultado es “No rechaza”. Esto nos indica que, al menos en este modelo, no podemos afirmar con certeza que los cambios en la tasa de interés dicten el ritmo del crecimiento económico de manera inmediata. Es probable que el efecto de las tasas tarde tiempo en sentirse rezagos o que dependa de otros factores externos que no metimos en esta prueba específica.</p>
<p>No pudimos comprobar estadísticamente que la deuda o las tasas de interés sean malas o determinantes negativos para el crecimiento por sí solas en este periodo. Esto nos deja ver que la economía mexicana es mucho más compleja y que estas variables probablemente interactúan con otras cosas como las exportaciones para afectar al PIB.</p>
<section id="regresión-múltiple" class="level2">
<h2 class="anchored" data-anchor-id="regresión-múltiple">REGRESIÓN MÚLTIPLE</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>formula_multi <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"Crecimiento_PIB ~"</span>, <span class="fu">paste</span>(variables_externas, <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>modelo_multi <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula_multi, <span class="at">data =</span> datos_limpios)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>resumen_multi <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo_multi)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>coeficientes_multi <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo_multi)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>tabla_coef_signif <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">names</span>(coeficientes_multi),</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Coeficiente =</span> <span class="fu">round</span>(coeficientes_multi, <span class="dv">4</span>),</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_valor =</span> <span class="fu">round</span>(<span class="fu">summary</span>(modelo_multi)<span class="sc">$</span>coefficients[, <span class="dv">4</span>], <span class="dv">4</span>),</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Significativo =</span> <span class="fu">summary</span>(modelo_multi)<span class="sc">$</span>coefficients[, <span class="dv">4</span>] <span class="sc">&lt;</span> <span class="fl">0.05</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tabla_coef_signif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         Variable Coeficiente P_valor
(Intercept)                           (Intercept)     -7.1507  0.2581
Exportaciones                       Exportaciones      0.0000  0.0813
Deuda_Externa                       Deuda_Externa      0.0000  0.0268
Reservas_Internacionales Reservas_Internacionales      0.0000  0.8135
FBKF                                         FBKF      0.0000  0.3428
TIIE                                         TIIE      0.3966  0.0136
Balance_fiscal                     Balance_fiscal      0.0000  0.9724
                         Significativo
(Intercept)                      FALSE
Exportaciones                    FALSE
Deuda_Externa                     TRUE
Reservas_Internacionales         FALSE
FBKF                             FALSE
TIIE                              TRUE
Balance_fiscal                   FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"R²:"</span>, <span class="fu">round</span>(resumen_multi<span class="sc">$</span>r.squared, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R²: 0.3422"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"R² ajustado:"</span>, <span class="fu">round</span>(resumen_multi<span class="sc">$</span>adj.r.squared, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R² ajustado: 0.1543"</code></pre>
</div>
</div>
</section>
<section id="gráfico-de-coeficientes" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-de-coeficientes">GRÁFICO DE COEFICIENTES</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>coef_sin_intercepto <span class="ot">&lt;-</span> coeficientes_multi[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>coef_ordenados <span class="ot">&lt;-</span> <span class="fu">sort</span>(coef_sin_intercepto)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="dv">2</span>))</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(coef_ordenados, </span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">names.arg =</span> <span class="fu">names</span>(coef_ordenados),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">horiz =</span> <span class="cn">TRUE</span>, <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">ifelse</span>(coef_ordenados <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"green"</span>, <span class="st">"red"</span>),</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Coeficiente"</span>,</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Impacto en Crecimiento PIB (Regresión Múltiple)"</span>,</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fu">min</span>(coef_ordenados)<span class="sc">*</span><span class="fl">1.2</span>, <span class="fu">max</span>(coef_ordenados)<span class="sc">*</span><span class="fl">1.2</span>))</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">0</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Partiendo de los resultados anteriores hicimos una regresión para observar que tanto peso tenían sin embargo es muy pequeño el peso que se tiene, tambien podemos observar que la deuda externa y la TIIE son las unicas significativas.</p>
</section>
</section>
<section id="análisis-de-residuales" class="level1">
<h1>ANÁLISIS DE RESIDUALES</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>residuales <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_multi)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>))</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(modelo_multi), residuales, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Valores ajustados"</span>, <span class="at">ylab =</span> <span class="st">"Residuales"</span>,</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Residuales vs Ajustados"</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(residuales, <span class="at">main =</span> <span class="st">"QQ-plot Residuales"</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(residuales, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(residuales, <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="at">breaks =</span> <span class="dv">15</span>,</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribución Residuales"</span>,</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Residuales"</span>, <span class="at">col =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="fu">mean</span>(residuales), <span class="fu">sd</span>(residuales)), <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(residuales, <span class="at">type =</span> <span class="st">"b"</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Orden"</span>, <span class="at">ylab =</span> <span class="st">"Residuales"</span>,</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Residuales vs Orden"</span>)</span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>shapiro_test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(residuales)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Shapiro-Wilk: W ="</span>, <span class="fu">round</span>(shapiro_test<span class="sc">$</span>statistic, <span class="dv">4</span>), </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">"p ="</span>, <span class="fu">round</span>(shapiro_test<span class="sc">$</span>p.value, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Shapiro-Wilk: W = 0.9916 p = 0.9976"</code></pre>
</div>
</div>
<p>Después de obtener los resultados de las regresiones y pruebas de hipótesis, sabíamos que no podíamos confiar ciegamente en los números sin antes hacer un check-up técnico al modelo. Para eso, generamos estas gráficas de análisis de residuales, que básicamente nos dicen si las suposiciones matemáticas que hicimos son válidas o si hay errores escondidos. La buena noticia es que las gráficas nos dieron luz verde para confiar en nuestro análisis.</p>
<p>Primero, nos fijamos en la gráfica de Residuales vs.&nbsp;Ajustados. Aquí lo que buscábamos era que los puntos azules estuvieran regados como una nube sin forma, y eso fue justo lo que encontramos. No vemos ningún patrón de embudo o curva extraña, los puntos están dispersos aleatoriamente alrededor de la línea roja del cero. Esto es excelente porque significa que la varianza de nuestros errores es constante no hay problemas graves de heterocedasticidad y que el modelo lineal fue la elección correcta para estos datos.</p>
<p>Luego, revisamos si los errores seguían una distribución Normal, lo cual es requisito para que las pruebas de hipótesis que hicimos antes sean válidas. En el QQ-plot, vemos que los círculos se alinean casi perfectamente sobre la línea diagonal roja. Aunque hay un par de puntos en las esquinas que se salen un poquito, la gran mayoría se comporta muy bien. Esto se confirma con el Histograma, donde la curva roja de la campana de Gauss cubre bastante bien las barras azules.</p>
<p>A partir de lo que habíamos obtenido algo nos hacía ruido por lo que decidimos investigar y encontramos que existe la curva de laffer razon Deuda-PIB así que decidimos hacerla para nuestros datos y comprobar una vez mas si tienen peso las variables en el crecimiento. El modelo utilizado es el siguiente:</p>
<p><span class="math display">\[
\ln(PIB_{pc})_t = \beta_0 + \beta_1 \ln(D\_PUB)_t + \beta_2 \ln(D\_PUB)^2_t + \beta_3 \ln(BF)_t + \beta_4 \ln(RESER)_t + \beta_5 \ln(FBKF)_t + \beta_6 \ln(TI)_t + \beta_7 \ln(EXPOR)_t + \varepsilon_t
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>datos_modelos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_PIB_pc =</span> <span class="fu">log</span>(PIB_PC),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_D_PUB =</span> <span class="fu">log</span>(Deuda_Externa),</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_D_PUB_sq =</span> (<span class="fu">log</span>(Deuda_Externa))<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_FBKF =</span> <span class="fu">log</span>(FBKF),</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_TIIE =</span> <span class="fu">log</span>(TIIE),</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_RESER =</span> <span class="fu">log</span>(Reservas_Internacionales),</span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">ln_EXPOR =</span> <span class="fu">log</span>(Exportaciones),</span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Balance_neg_dummy =</span> <span class="fu">ifelse</span>(Balance_fiscal <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">select</span>(ln_PIB_pc, ln_D_PUB, ln_D_PUB_sq, ln_FBKF, ln_TIIE, </span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a>         ln_RESER, ln_EXPOR, Balance_neg_dummy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Debido a que es un modelo logaritmico no podiamos aplicarle el logaritmo a el balance debido a que contiene datos negativos por lo que decidimos hacer la variable dummy y utilizamos la parte negativa.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>modelo_parsimonioso <span class="ot">&lt;-</span> <span class="fu">lm</span>(ln_PIB_pc <span class="sc">~</span> ln_D_PUB <span class="sc">+</span> ln_D_PUB_sq <span class="sc">+</span> ln_RESER <span class="sc">+</span> ln_FBKF <span class="sc">+</span> ln_EXPOR <span class="sc">+</span> Balance_neg_dummy, <span class="at">data =</span> datos_modelos)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_parsimonioso)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ln_PIB_pc ~ ln_D_PUB + ln_D_PUB_sq + ln_RESER + 
    ln_FBKF + ln_EXPOR + Balance_neg_dummy, data = datos_modelos)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.032323 -0.004134 -0.000039  0.009328  0.019128 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -12.981882   6.411990  -2.025 0.055212 .  
ln_D_PUB            1.350846   0.437902   3.085 0.005414 ** 
ln_D_PUB_sq        -0.024434   0.007838  -3.117 0.005020 ** 
ln_RESER           -0.080150   0.021023  -3.812 0.000952 ***
ln_FBKF             0.220169   0.039010   5.644 1.13e-05 ***
ln_EXPOR            0.255268   0.054942   4.646 0.000125 ***
Balance_neg_dummy  -0.042498   0.010319  -4.118 0.000452 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01303 on 22 degrees of freedom
Multiple R-squared:  0.9492,    Adjusted R-squared:  0.9354 
F-statistic: 68.57 on 6 and 22 DF,  p-value: 4.088e-13</code></pre>
</div>
</div>
<p>Realizando la regresión múltiple, lo primero que nos llamó la atención fue la increíble precisión con la que logramos explicar el comportamiento del PIB per cápita. El coeficiente de determinación R-cuadrada nos dio un valor de 0.9492, lo que significa que las variables que elegimos deuda, inversión, exportaciones y reservas explican casi el 95% de la variabilidad en el ingreso promedio de los mexicanos. Esto es un gran logro para el proyecto, porque confirma que no estamos dejando fuera factores importantes y que el modelo ajusta casi a la perfección con la realidad histórica de los datos. Además, el P-valor global es extremadamente pequeño <span class="math inline">\(4.088 \times 10^{-13}\)</span>, lo que nos asegura que la relación que encontramos no es producto del azar.</p>
<p>Uno de los hallazgos más interesantes y complejos que encontramos tiene que ver con la Deuda Pública. Decidimos incluir tanto el término lineal como el cuadrático para probar si el efecto cambiaba con el tiempo, y los resultados confirmaron nuestra sospecha de una relación no lineal. El coeficiente de la deuda simple (ln_D_PUB) es positivo 1.35, pero el de la deuda al cuadrado (ln_D_PUB_sq) es negativo -0.024. Económicamente, esto nos dice que la deuda tiene un comportamiento de “U invertida”: en niveles bajos, endeudarse ayuda a impulsar el crecimiento signo positivo, pero a medida que la deuda crece excesivamente, el efecto se revierte y empieza a frenar el PIB per cápita signo negativo.</p>
<p>Por otro lado, confirmamos quiénes son los verdaderos motores de la economía. Tanto la Formación Bruta de Capital Fijo (ln_FBKF) como las Exportaciones (ln_EXPOR) mostraron coeficientes positivos y altamente significativos con el nivel de significancia más alto de tres asteriscos. Específicamente, por cada 1% que aumentan las exportaciones, el PIB per cápita sube aproximadamente 0.25%, mientras que la inversión lo hace subir un 0.22%. Esto nos permite afirmar con evidencia estadística que la apertura comercial y la inversión física son las variables más nobles y efectivas para generar riqueza real en el país.</p>
<p>Finalmente, las variables de control financiero nos mostraron el costo de la inestabilidad. La variable dummy del Balance Fiscal (Balance_neg_dummy) arrojó un coeficiente negativo de -0.042, lo que valida que los años con déficit fiscal castigan el crecimiento del ingreso per cápita. También notamos que las Reservas Internacionales (ln_RESER) tienen una relación negativa significativa con el PIB per cápita -0.08 interpretamos esto no como que las reservas sean malas, sino que su acumulación masiva suele ocurrir en periodos de incertidumbre o crisis cambiaria, cuando el crecimiento económico tiende a ser bajo, capturando así una correlación contracíclica en el modelo, ademas que tambien se debe a que es dinero un poco estancado ya que esta en dolares y no se invierte en el país por lo que no genera crecimiento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">=== UMBRAL ÓPTIMO DE DEUDA  ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== UMBRAL ÓPTIMO DE DEUDA  ===</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>calcular_umbral <span class="ot">&lt;-</span> <span class="cf">function</span>(modelo) {</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  coefs <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  ln_umbral <span class="ot">&lt;-</span> <span class="sc">-</span>coefs[<span class="st">"ln_D_PUB"</span>] <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> coefs[<span class="st">"ln_D_PUB_sq"</span>])</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  umbral_original <span class="ot">&lt;-</span> <span class="fu">exp</span>(ln_umbral)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(umbral_original)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>umbral_parsimonioso <span class="ot">&lt;-</span> <span class="fu">calcular_umbral</span>(modelo_parsimonioso)</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Umbral óptimo de deuda:"</span>, <span class="fu">round</span>(umbral_parsimonioso, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Umbral óptimo de deuda: 1.012276e+12 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>deuda_promedio <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">exp</span>(datos_modelos<span class="sc">$</span>ln_D_PUB))</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Deuda promedio en el período:"</span>, <span class="fu">round</span>(deuda_promedio, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Deuda promedio en el período: 2.104546e+12 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>diferencia_porcentaje <span class="ot">&lt;-</span> (umbral_parsimonioso<span class="sc">/</span>deuda_promedio <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"→ Diferencia respecto al promedio:"</span>, <span class="fu">round</span>(diferencia_porcentaje, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>→ Diferencia respecto al promedio: -51.9 %</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos_modelos, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">exp</span>(ln_D_PUB), <span class="at">y =</span> <span class="fu">exp</span>(ln_PIB_pc))) <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> umbral_parsimonioso, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"green"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Curva de Laffer: Relación Deuda-Crecimiento"</span>,</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"Umbral óptimo:"</span>, <span class="fu">round</span>(umbral_parsimonioso, <span class="dv">2</span>)),</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Deuda Total"</span>, </span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"PIB per cápita"</span>) <span class="sc">+</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Basándonos en los coeficientes de nuestro modelo de regresión donde encontramos que la deuda tiene un efecto positivo al principio pero negativo después, decidimos calcular dónde está exactamente ese límite. Queríamos encontrar el punto optimo de deuda o el nivel de deuda que maximiza el crecimiento del PIB per cápita antes de empezar a perjudicarlo. El resultado de nuestro cálculo arrojó un Umbral Óptimo de aproximadamente <span class="math inline">\(1.01 \times 10^{12}\)</span> un billón.</p>
<p>Sin embargo, al comparar este número teórico con la realidad, nos llevamos una sorpresa preocupante. La Deuda Promedio observada durante el periodo de estudio fue de <span class="math inline">\(2.10 \times 10^{12}\)</span> 2.1 billones. Esto significa que, en promedio, México ha estado operando con un nivel de endeudamiento que es más del doble del nivel óptimo sugerido por nuestro modelo. Estadísticamente, estamos situados un 51.9% por encima del punto de eficiencia.</p>
<p>Este hallazgo es crucial, nos indica que México ya cruzó la cima de la curva de Laffer de la deuda. Al estar tan pasados del umbral óptimo del lado derecho de la U invertida, cada peso adicional que el país pide prestado ya no contribuye a generar más riqueza per cápita, al contrario, es probable que los costos del servicio de la deuda y la incertidumbre financiera estén restando dinamismo a la economía. Básicamente, demostramos con datos que el endeudamiento excesivo ha dejado de ser una palanca de desarrollo para convertirse en una carga.</p>
</section>
<section id="anova-para-deuda-externa-por-sexenios" class="level1">
<h1>ANOVA PARA DEUDA EXTERNA POR SEXENIOS</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="st">"Sexenio"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(datos)) {</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  datos<span class="sc">$</span>Sexenio <span class="ot">&lt;-</span> <span class="fu">cut</span>(datos<span class="sc">$</span>...<span class="dv">1</span>,</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1993</span>, <span class="dv">2000</span>, <span class="dv">2006</span>, <span class="dv">2012</span>, <span class="dv">2018</span>, <span class="dv">2024</span>),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"1994-2000"</span>, <span class="st">"2001-2006"</span>, <span class="st">"2007-2012"</span>, </span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"2013-2018"</span>, <span class="st">"2019-2024"</span>))</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>anova_deuda <span class="ot">&lt;-</span> <span class="fu">aov</span>(Deuda_Externa <span class="sc">~</span> Sexenio, <span class="at">data =</span> datos)</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>summary_anova_deuda <span class="ot">&lt;-</span> <span class="fu">summary</span>(anova_deuda)</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"ANOVA - Deuda Externa por Sexenio:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ANOVA - Deuda Externa por Sexenio:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_anova_deuda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df    Sum Sq   Mean Sq F value   Pr(&gt;F)    
Sexenio      4 6.609e+25 1.652e+25   59.16 4.42e-12 ***
Residuals   24 6.702e+24 2.792e+23                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(summary_anova_deuda[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>] <span class="sc">&lt;</span> <span class="fl">0.05</span>) {</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"Prueba post-hoc Tukey (diferencias entre sexenios):"</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  tukey_deuda <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(anova_deuda)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(tukey_deuda)</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="dv">2</span>))</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(tukey_deuda, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>))</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Prueba post-hoc Tukey (diferencias entre sexenios):"
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Deuda_Externa ~ Sexenio, data = datos)

$Sexenio
                            diff           lwr          upr     p adj
2001-2006-1994-2000 7.109833e+10 -871581671895 1.013778e+12 0.9994176
2007-2012-1994-2000 4.146850e+11 -527995005229 1.357365e+12 0.6961099
2013-2018-1994-2000 2.292130e+12 1349449994771 3.234810e+12 0.0000020
2019-2024-1994-2000 3.819517e+12 2876836661438 4.762197e+12 0.0000000
2007-2012-2001-2006 3.435867e+11 -555223451949 1.242397e+12 0.7912912
2013-2018-2001-2006 2.221032e+12 1322221548051 3.119842e+12 0.0000015
2019-2024-2001-2006 3.748418e+12 2849608214718 4.647228e+12 0.0000000
2013-2018-2007-2012 1.877445e+12  978634881385 2.776255e+12 0.0000215
2019-2024-2007-2012 3.404832e+12 2506021548051 4.303642e+12 0.0000000
2019-2024-2013-2018 1.527387e+12  628576548051 2.426197e+12 0.0003622</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>p_deuda <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> Sexenio, <span class="at">y =</span> Deuda_Externa, <span class="at">fill =</span> Sexenio)) <span class="sc">+</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Deuda Externa por Sexenio"</span>, </span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Sexenio Presidencial"</span>, </span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Deuda Externa"</span>) <span class="sc">+</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_deuda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>estadisticas_deuda <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Deuda_Externa <span class="sc">~</span> Sexenio, <span class="at">data =</span> datos,</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">FUN =</span> <span class="cf">function</span>(x) <span class="fu">c</span>(<span class="at">Media =</span> <span class="fu">mean</span>(x), </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">SD =</span> <span class="fu">sd</span>(x),</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">Min =</span> <span class="fu">min</span>(x),</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">Max =</span> <span class="fu">max</span>(x),</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">n =</span> <span class="fu">length</span>(x)))</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Estadísticas Deuda Externa por Sexenio:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Estadísticas Deuda Externa por Sexenio:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(estadisticas_deuda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Sexenio Deuda_Externa.Media Deuda_Externa.SD Deuda_Externa.Min
1 1994-2000        7.395600e+11     8.073691e+10      6.384000e+11
2 2001-2006        8.106583e+11     6.564598e+10      7.445200e+11
3 2007-2012        1.154245e+12     5.281079e+11      4.348700e+11
4 2013-2018        3.031690e+12     9.509744e+11      1.731850e+12
5 2019-2024        4.559077e+12     3.841806e+11      4.109610e+12
  Deuda_Externa.Max Deuda_Externa.n
1      8.145000e+11    5.000000e+00
2      8.922000e+11    6.000000e+00
3      1.685130e+12    6.000000e+00
4      4.048750e+12    6.000000e+00
5      5.150450e+12    6.000000e+00</code></pre>
</div>
</div>
<p>Para entender mejor el comportamiento de la deuda, decidimos no verla solo como una línea continua, sino partirla por administraciones o sexenios. Hicimos esto porque sospechábamos que las decisiones políticas de cada gobierno afectaban los niveles de endeudamiento de forma distinta. Al generar este diagrama de cajas, confirmamos visualmente que existen dos eras muy marcadas en la historia reciente de México.</p>
<p>Lo primero que notamos es la Era de Estabilidad 1994-2006. Si observan las dos primeras cajas , son pequeñitas y están muy abajo. Esto nos dice que durante esos dos sexenios, la deuda externa se mantuvo baja y, lo más importante, muy estable poca varianza. Los promedios los puntos rojos casi no se movieron. En ese entonces, la deuda no era un tema que generara ruido en nuestras pruebas estadísticas.</p>
<p>Sin embargo, a partir del sexenio <strong>2007-2012</strong>, vemos el cambio drástico. La caja se hace más alta y sube de nivel, lo cual coincide con la Crisis Financiera de 2008 que nos obligó a pedir prestado. Pero lo más impactante viene después: en el periodo <strong>2013-2018</strong>, la caja es enorme. Esto significa que no solo subió la deuda promedio, sino que hubo una volatilidad gigantesca, hubo años donde la deuda creció descontroladamente.</p>
<p>Finalmente, el sexenio actual <strong>2019-2024</strong> muestra los niveles más altos de la historia, con la caja flotando hasta arriba, cerca de los 5 billones. Aunque la caja es un poco más compacta que la anterior menos volátil, el “piso” de la deuda ya es altísimo.</p>
<p>Esta gráfica prueba que la media de la deuda no es constante en el tiempo (heterogeneidad). Pasamos de una política de deuda cautelosa a una de endeudamiento acelerado. Esto respalda por qué en nuestro modelo de regresión la deuda salió tan significativa y por qué encontramos ese comportamiento de “U invertida”: los niveles actuales las cajas de la derecha ya están en la zona donde la deuda empieza a pesarle al crecimiento.</p>
<section id="anova-para-pib-per-cápita-por-sexenios" class="level2">
<h2 class="anchored" data-anchor-id="anova-para-pib-per-cápita-por-sexenios">ANOVA PARA PIB PER CÁPITA POR SEXENIOS</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>anova_pibpc <span class="ot">&lt;-</span> <span class="fu">aov</span>(PIB_PC <span class="sc">~</span> Sexenio, <span class="at">data =</span> datos)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>summary_anova_pibpc <span class="ot">&lt;-</span> <span class="fu">summary</span>(anova_pibpc)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"ANOVA - PIB per cápita por Sexenio:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ANOVA - PIB per cápita por Sexenio:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_anova_pibpc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df    Sum Sq   Mean Sq F value  Pr(&gt;F)    
Sexenio      4 1.279e+09 319814731   7.749 0.00037 ***
Residuals   24 9.906e+08  41273894                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(summary_anova_pibpc[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>] <span class="sc">&lt;</span> <span class="fl">0.05</span>) {</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"Prueba post-hoc Tukey (diferencias entre sexenios):"</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  tukey_pibpc <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(anova_pibpc)</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(tukey_pibpc)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="dv">2</span>))</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(tukey_pibpc, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>))</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Prueba post-hoc Tukey (diferencias entre sexenios):"
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = PIB_PC ~ Sexenio, data = datos)

$Sexenio
                         diff         lwr       upr     p adj
2001-2006-1994-2000  8782.633  -2678.0475 20243.314 0.1934369
2007-2012-1994-2000 11106.633   -354.0475 22567.314 0.0606714
2013-2018-1994-2000 19162.133   7701.4525 30622.814 0.0004426
2019-2024-1994-2000 17581.300   6120.6192 29041.981 0.0012151
2007-2012-2001-2006  2324.000  -8603.3304 13251.330 0.9692898
2013-2018-2001-2006 10379.500   -547.8304 21306.830 0.0683078
2019-2024-2001-2006  8798.667  -2128.6638 19725.997 0.1575536
2013-2018-2007-2012  8055.500  -2871.8304 18982.830 0.2242076
2019-2024-2007-2012  6474.667  -4452.6638 17401.997 0.4266985
2019-2024-2013-2018 -1580.833 -12508.1638  9346.497 0.9926559</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>p_pibpc <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> Sexenio, <span class="at">y =</span> PIB_PC, <span class="at">fill =</span> Sexenio)) <span class="sc">+</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PIB per cápita por Sexenio"</span>, </span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Sexenio Presidencial"</span>, </span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"PIB per cápita"</span>) <span class="sc">+</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_pibpc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-28-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>estadisticas_pibpc <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(PIB_PC <span class="sc">~</span> Sexenio, <span class="at">data =</span> datos,</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">FUN =</span> <span class="cf">function</span>(x) <span class="fu">c</span>(<span class="at">Media =</span> <span class="fu">mean</span>(x), </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">SD =</span> <span class="fu">sd</span>(x),</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">Min =</span> <span class="fu">min</span>(x),</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">Max =</span> <span class="fu">max</span>(x),</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">n =</span> <span class="fu">length</span>(x)))</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Estadísticas PIB per cápita por Sexenio:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Estadísticas PIB per cápita por Sexenio:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(estadisticas_pibpc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Sexenio PIB_PC.Media  PIB_PC.SD PIB_PC.Min PIB_PC.Max   PIB_PC.n
1 1994-2000   167949.200   9652.197 154237.000 179250.000      5.000
2 2001-2006   176731.833   4039.928 172794.000 183887.000      6.000
3 2007-2012   179055.833   5894.991 169470.000 184876.000      6.000
4 2013-2018   187111.333   3815.005 181630.000 191885.000      6.000
5 2019-2024   185530.500   7612.921 172140.000 192311.000      6.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>p_medias <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos, <span class="fu">aes</span>(<span class="at">x =</span> Sexenio, <span class="at">y =</span> PIB_PC, <span class="at">fill =</span> Sexenio)) <span class="sc">+</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal, <span class="at">geom =</span> <span class="st">"pointrange"</span>, <span class="at">size =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Medias de PIB per cápita por Sexenio"</span>,</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Puntos: medias, Barras: IC 95%"</span>,</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Sexenio Presidencial"</span>,</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"PIB per cápita"</span>) <span class="sc">+</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Proyecto_Final_files/figure-html/unnamed-chunk-28-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Al igual que hicimos con la deuda, decidimos desglosar el ingreso promedio de los mexicanos PIB per cápita por administraciones presidenciales para ver si realmente estamos mejor con el paso del tiempo. Esta gráfica de cajas nos cuenta una historia muy clara de crecimiento, pero también de los riesgos que hemos enfrentado en cada periodo. Lo primero que notamos con satisfacción es que la tendencia general es ascendente. Si se fijan en los puntos rojos que son los promedios, cada sexenio supera al anterior. Esto significa que, a pesar de las crisis y problemas, la riqueza promedio del país ha seguido una trayectoria de crecimiento a largo plazo.</p>
<p>Sin embargo, al analizar la forma de las cajas, la dispersión, encontramos diferencias clave en la estabilidad económica de cada gobierno. Por ejemplo, el sexenio 2001-2006 la segunda caja amarilla destaca por ser el más compacto, esto nos dice que fue un periodo de mucha estabilidad macroeconómica donde el ingreso no varió bruscamente. En contraste, el sexenio 2007-2012 la caja verde es mucho más alto, reflejando la volatilidad que trajo la crisis financiera de 2008.</p>
<p>Lo más interesante y dramático aparece en el sexenio actual 2019-2024. Aunque la caja rosa alcanza el nivel promedio más alto de la historia el punto rojo está más arriba que todos, también tiene un bigote o línea inferior larguísima que cae hasta los 170,000 pesos. Esto es la huella estadística de la pandemia de 2020: un desplome brutal que, aunque fue temporal, generó una dispersión enorme en los datos de este periodo.</p>
<p>Si bien el PIB per cápita promedio es hoy más alto que hace 20 años, la gráfica nos muestra que el crecimiento no es gratuito, viene acompañado de periodos de alta volatilidad. Mientras que algunos gobiernos ofrecieron estancamiento con estabilidad como el de 2001-2006, otros, como el actual y el de 2007-2012, lograron promedios más altos pero a costa de sufrir choques externos violentos que estiraron la distribución de los datos hacia abajo.</p>
</section>
</section>
<section id="conclusión" class="level1">
<h1>Conclusión</h1>
<p>Al finalizar este estudio estadístico sobre los determinantes del crecimiento económico de México, podemos afirmar que hemos cumplido con el objetivo general planteado: evaluar cuantitativamente la relación entre las variables macroeconómicas y el desempeño del PIB. La evidencia empírica recabada nos permite aceptar la Hipótesis General <span class="math inline">\(H_1\)</span>, confirmando que la Deuda Externa, las Exportaciones, las Reservas Internacionales y la Inversión (FBKF) tienen un efecto estadísticamente significativo en la economía, aunque la naturaleza de estos efectos resultó ser mucho más compleja de lo que anticipábamos inicialmente.</p>
<p>Nuestros hallazgos se pueden resumir en tres pilares fundamentales:</p>
<p><strong>1. Los Motores del Crecimiento: Comercio e Inversión</strong> Tal como sugería la teoría económica, nuestro modelo econométrico con una <span class="math inline">\(R^2\)</span> del 95% demostró que las Exportaciones y la Formación Bruta de Capital Fijo (FBKF) son los verdaderos impulsores del bienestar. Ambas variables presentaron coeficientes positivos y altamente significativos, validando que la apertura comercial y la inversión en capital físico son las rutas más efectivas para incrementar el PIB per cápita. La correlación positiva observada desde el inicio del análisis no fue espuria, sino causal.</p>
<p><strong>2. La “Paradoja” de la Deuda y el Umbral Óptimo</strong> El descubrimiento más crítico del equipo fue la relación no lineal de la Deuda Pública. Mientras que nuestras pruebas de hipótesis simples iniciales no lograban identificar un efecto negativo directo, la regresión cuadrática reveló un comportamiento de “U invertida”. Esto significa que la deuda no es mala, sino que tiene un límite. Nuestro cálculo del Punto Óptimo <span class="math inline">\(\approx 1\)</span> billón frente al promedio observado <span class="math inline">\(\approx 2.1\)</span> billones es una alerta estadística: México ha operado, en promedio, un 51.9% por encima de su nivel óptimo de endeudamiento. Esto nos lleva a concluir que, en los últimos sexenios, la deuda ha dejado de ser una palanca de crecimiento para convertirse en un factor de saturación que, marginalmente, ya no aporta al PIB per cápita.</p>
<p><strong>3. Deterioro Fiscal y Volatilidad Estructural</strong> El análisis de intervalos de confianza nos mostró un déficit fiscal estructural, el intervalo del balance siempre fue negativo, y los diagramas de caja por sexenio evidenciaron un cambio de régimen a partir de 2008. Pasamos de una etapa de estabilidad financiera a una de alta volatilidad y endeudamiento acelerado. Si bien el PIB per cápita ha mantenido una tendencia creciente a largo plazo, los bigotes de las cajas en los sexenios recientes especialmente 2019-2024 demuestran que el crecimiento actual es mucho más vulnerable a choques externos que en el pasado.</p>
<p>Finalmente, respaldamos todas estas conclusiones en la robustez de nuestros métodos. La convergencia casi perfecta entre los estimadores de Momentos (MOM) y Máxima Verosimilitud (MLE), sumada a un análisis de residuales que confirmó normalidad y homocedasticidad, nos garantiza que estos resultados no son producto del azar ni de errores de especificación.</p>
<p>El proyecto demuestra estadísticamente que para que México retome una senda de crecimiento acelerado, no basta con seguir endeudándose pues ya cruzamos el límite productivo, la estrategia debe centrarse en potenciar las variables reales Exportaciones y FBKF y recuperar la disciplina fiscal que se perdió hace más de una década.</p>
<section id="bibliografía" class="level2">
<h2 class="anchored" data-anchor-id="bibliografía">Bibliografía</h2>
<p>Soto, V. G. (2020). La curva de Laffer en la relación dedua externa-crecimiento económico de México 1970- 2017. Revista mexicana de economía y finanzas, 205-225.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>